### ISSUE TITLE
Error with webpack 

### ISSUE THREAD

**Issue by niksmac** [LucasBassetti/react-simple-chatbot#8]
When I run `npm run build` I get the following error.

```
› npm run build

> react-simple-chatbot@0.1.10 build /Users/yesthis/rchat
> webpack --config webpack.config.prod.js

clean-webpack-plugin: /Users/yesthis/rchat/dist has been removed.
Hash: 6e4e3f42d328d295e90f
Version: webpack 1.15.0
Time: 4153ms
                  Asset     Size  Chunks             Chunk Names
react-simple-chatbot.js  1.09 MB       0  [emitted]  main
    + 149 hidden modules

ERROR in react-simple-chatbot.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
    at /Users/yesthis/rchat/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:81:19
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/yesthis/rchat/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at Compilation.applyPluginsAsync (/Users/yesthis/rchat/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/Users/yesthis/rchat/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/Users/yesthis/rchat/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/yesthis/rchat/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/yesthis/rchat/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:52:16
    at done (/Users/yesthis/rchat/node_modules/async/lib/async.js:246:17)
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:44:16
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:52:16
    at done (/Users/yesthis/rchat/node_modules/async/lib/async.js:246:17)
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:44:16
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:52:16
    at done (/Users/yesthis/rchat/node_modules/async/lib/async.js:246:17)
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:44:16
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:52:16
    at done (/Users/yesthis/rchat/node_modules/async/lib/async.js:246:17)
    at /Users/yesthis/rchat/node_modules/async/lib/async.js:44:16
    at /Users/yesthis/rchat/node_modules/webpack/lib/Compilation.js:332:10
```

**Comment by LucasBassetti** [comment]
Hi,

Did you run `npm install` before the build command?

**Comment by niksmac** [comment]
Yes I did `npm install`

```
in rchat/ on master 
› sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

in rchat/ on master 
› node -v                
v8.1.2

in rchat/ on master 
› npm --version          
5.0.3
```

**Comment by LucasBassetti** [comment]
Hi,

I update the webpack configs. Please pull the last change, try again and tell me if it works.

**Comment by niksmac** [comment]
Now I get a better error. It might be my system specific. I will crosscheck. In the meantime pleas go through this and check if it rings any bell. https://pastebin.com/whrhe78S 
TA

**Comment by LucasBassetti** [comment]
the `npm start` will not work because I use the `app` folder for development. You will need create your own.

You can make some like that

![image](https://user-images.githubusercontent.com/1014326/27261509-87bfd5ea-541a-11e7-9fc1-7afb7d247679.png)

**Comment by niksmac** [comment]
Can you provide some guidelines? May be upload a sample `app` folder?

**Comment by LucasBassetti** [comment]
Done. Please pull the last change and run `npm start` again
